// generated by "sampctl package generate"

#include "optidraw.inc"
#include "od_entry.inc"
#include "od_hooks.inc"
#include "od_impl.inc"

main() 
{
	// write tests for libraries here and run "sampctl package run"
}
